#!/usr/bin/env python
import tempfile
import sys
import os

from clint import arguments
from clint.textui import puts, colored

from webscrape import get_thing_details
from download import download_thing_files
from zip import zipdir


def display_thing_details(thing_details):
    puts('\tURL: %s' % thing_details['url'])
    puts('\tID: %s' % thing_details['id'])
    puts('\tFiles: %s' % len(thing_details['files']))


def main(thing_id):
    try:
        puts('Retrieving thing details...\n')

        thing_details = get_thing_details(thing_id)
        display_thing_details(thing_details)

        # Create temp folder
        puts('\nDownloading thing files...\n')

        with tempfile.TemporaryDirectory() as tempdir:
            # Download all the thing files...
            download_thing_files(thing_details['files'], tempdir)
            puts('\nBuidling %s.zip...' % thing_id)
            zipdir(tempdir, thing_id)
            puts(colored.green('DONE!'))
    except Exception as e:
        puts(colored.red(e.message))


if __name__ == '__main__':
    import logging.config
    loglevel = os.environ.get('THINGY_DL_LOGLEVEL', 'INFO')
    logging.basicConfig(stream=sys.stdout, level=logging.getLevelName(loglevel))

    args = arguments.Args()
    thing_id_arg = args.get(0)

    if thing_id_arg is None or len(args) != 1:
        print('USAGE: thingy-dl <thing-id>')
        exit(1)

    main(thing_id_arg)
